-- Ensure all tobacco-related columns exist in mixes table
-- Uses IF NOT EXISTS so safe to re-run

ALTER TABLE mixes ADD COLUMN IF NOT EXISTS brand VARCHAR(255) DEFAULT '';
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS flavor VARCHAR(255) DEFAULT '';
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS price DECIMAL(10,2) DEFAULT 0;
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0;
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS unit VARCHAR(20) DEFAULT 'gram';
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS min_stock_threshold INTEGER DEFAULT 5;
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS auto_reorder_enabled BOOLEAN DEFAULT false;
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS weight_grams INTEGER DEFAULT 50;
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS emoji VARCHAR(10) DEFAULT '';
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS category VARCHAR(50) DEFAULT 'Основные';
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS color VARCHAR(20) DEFAULT '';
ALTER TABLE mixes ADD COLUMN IF NOT EXISTS strength INTEGER DEFAULT 5;
